#Server config
server:
  servlet:
    context-path: /fervour-todo
  port: 9001
  connection-timeout: 10000
  
#Spring configs
spring:
  #DataSource
  datasource:
    url: jdbc:mysql://localhost:33099/env_dva1
    username: root
    password: root
  #JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform:  org.hibernate.dialect.MySQL5InnoDBDialect
    
  #logging
logging:
  level:
    org.springframework: error
    com.personal.fervour: debug
    org.hibernate: error
  file: ./logs/fervour_personal.log
  pattern:
    file: "%d %p %c{1.} [%t] %m%n"
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"